I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 82, in script
  File "game/script.rpy", line 82, in <module>
NameError: name 'normal' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 82, in script
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\ast.py", line 1150, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\ast.py", line 1109, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\User\Documents\chadisland development\renpy-7.1.3-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 82, in <module>
NameError: name 'normal' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
Chad Island 1.0
Sun Dec 02 13:33:40 2018
